comment: false
github_checks:
  annotations: false
  
  save-workflow:
    needs: run
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Guardar información del workflow
        run: node saveWorkflow.js